### ISSUE TITLE
Mod should ideally check if it's installed on a headless OR that the mod user is hosting the session before changing anything 

### ISSUE THREAD

**Issue by Nytra** [LeCloutPanda/SoNoHeadCrash#1]
The way it is right now I think stuff could get changed in sessions the user is not hosting which could be bad

**Comment by LeCloutPanda** [comment]
Yeah, I agree with you on that one and will push an update out soon.

Thanks for notifying me on that one, it completely slipped my mind considering it should only be run on headless servers but not thinking about the fact people would most likely just install it anyway.

**Comment by LeCloutPanda** [comment]
Fixed with [latest release](https://github.com/LeCloutPanda/SoNoHeadCrash/releases/tag/v1.0.1), thank you for the suggestion.
